name: Publish Package

on:
  push:
    branches:
      - 'main'  # 仅在以版本标签推送时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 或你需要的版本

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
            version: 8.6.12

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build  # 确保在 package.json 中有相应的 build 脚本

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # 使用秘密环境变量